[profile.default]
src = "src"
out = "out"
libs = ["lib"]

optimizer = false
optimizer_runs = 200

remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts/",
    "ds-test/=lib/ds-test/src/",
    "@forge/=lib/forge-std/src/",
    "@hyperbridge/core/=lib/hyperbridge-sdk/packages/core/",
]

fs_permissions = [{ access = "read-write", path = "deployments.toml"}]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
